print("hello")
print("Rathinam Global University")
print("Name\t:,Rakshitha s")
print("reg no\s:","Rcas2026BAI217")
print("Blood Group\n:","O+ve")
print("Department\s:","AIDS")
print("Class:","C29")
print("Subject:","Python")
print("College Location:","Eachanari")
print("Institution:","RGU")
print("Pincode:","641001")
print("Phone no:","9586643810")
print("District Name:","Coimbatore")
print("State Name:","Tamilnadu")
print("Father Name:","Srinivasan")

